app/models.py
from . import db, login_manager
from flask_login import UserMixin
from flask import redirect, url_for


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(), unique=True, nullable=False)
    password = db.Column(db.String(), nullable=False)


# Required by flask-login
@login_manager.user_loader
def load_user(id):
    return db.session.get(User, int(id))


# Customized to disable flash message.
@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for("main.login"))

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
from .models import User


class RegistrationForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    confirm_password = PasswordField(
        "Confirm Password", validators=[DataRequired(), EqualTo("password")]
    )
    submit = SubmitField("Sign Up")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError("That email is already taken.")


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember = BooleanField("Remember Me")
    submit = SubmitField("Login")


class SearchForm(FlaskForm):
    search = StringField("Search")

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from . import config

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()


def create_app(config_object=config):
    # create and configure the app
    app = Flask(__name__)
    app.config.from_object(config_object)

    # initialize
    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    # blueprints
    from .routes import main

    app.register_blueprint(main)

    # Create db + tables
    # Must appear after db init and blueprint registration.
    with app.app_context():
        db.create_all()

    # error handlers
    @app.errorhandler(401)
    def internal_error(error):
        return render_template("errors/401.html", title="Unauthorized Access"), 401

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("errors/404.html", title="Page not found"), 404

    @app.errorhandler(405)
    def page_not_found(error):
        return render_template("errors/405.html", title="Method Not Allowed"), 405

    @app.errorhandler(500)
    def internal_error(error):
        db.session.rollback()
        return render_template("errors/500.html", title="Internal Server Error"), 500

    return app

app/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from .forms import RegistrationForm, LoginForm, SearchForm
from .models import User
from flask_login import login_user, logout_user, login_required, current_user
from . import db, bcrypt
import multiprocessing
import os

main = Blueprint("main", __name__)


@main.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created! You are now able to log in.", "success")
        return redirect(url_for("main.login"))
    return render_template("auth/register.html", title="Register", form=form)


@main.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.dashboard"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for("main.dashboard"))
        else:
            flash("Login unsuccessful. Check email and password.", "danger")
    return render_template("auth/login.html", title="Login", form=form)


@main.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.login"))


@main.route("/")
@login_required
def dashboard():
    return render_template("dashboard.html", title="Dashboard")


@main.route("/music")
@login_required
def music():
    # search = request.args.get("search")
    # search_form = SearchForm()
    # search_form.search.data = search
    return render_template("music.html", title="Music")

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="{{ url_for('static', filename='favicon.ico') }}" rel="icon" type="image/x-icon">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-icons.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  {% if title %}
  <title>{{ title }} - {{ config["SITE_NAME"] }}</title>
  {% else %}
  <title>{{ config["SITE_NAME"] }}</title>
  {% endif %}
</head>

<body>
  <div class="container">
    {% include "partials/nav.html" %}
    {% include "partials/flash.html" %}
    {% block content %}{% endblock %}
    {% include "partials/footer.html" %}
  </div>
</body>

</html>

app/templates/dashboard.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-7">

        <h1 class="pb-3">Hi!</h1>

        <div class="p-5 border rounded border-5 border-info-subtle shadow">
            <h1 class="h3 mb-3">Music for you</h1>
            <p>Explore personalized recommendations based on your listening history and preferences!</p>
            <a class="btn btn-info" href="{{ url_for('main.music') }}"><i class="bi bi-eye"></i> View</a>
        </div>
        
<div class="mt-5 p-5 border rounded border-5 border-success-subtle shadow">
    <h1 class="h3 mb-3">
        Statistics
    </h1>
    <table class="table border-2 border-dark-subtle">
        <tbody class="border-top border-top-2 border-dark-subtle">
            <tr>
                <td>
                    Today 
                </td>
                <td class="text-end">
                    <strong>123</strong>
                </td>
            </tr>
            <tr>
                <td>
                    This month
                </td>
                <td class="text-end">
                    <strong>123</strong>
                </td>
            </tr>
        </tbody>
    </table>
        </div>




    </div>
    
</div>


{% endblock %}

app/templates/music.html
{% extends "base.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Streamlit App</title>
</head>
<body>
    <h1 class="h3 mb-3">Streamlit Embedded App</h1>
    <iframe src="http://localhost:8501" width="100%" height="800"></iframe>
</body>
</html>
{% endblock %}

app/templates/partials/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="mt-3">
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

app/templates/partials/footer.html
<footer class="py-1 my-5 border-top">
    <div class="text-muted small">&copy; {{ config["SITE_NAME"] }}</div>
</footer>

app/templates/partials/nav.html
<header id="nav" class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="{{ url_for('main.dashboard') }}"
        class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#ff0097" class="bi bi-file-music-fill" viewBox="0 0 16 16">
            <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2m-.5 4.11v1.8l-2.5.5v5.09c0 .495-.301.883-.662 1.123C7.974 12.866 7.499 13 7 13s-.974-.134-1.338-.377C5.302 12.383 5 11.995 5 11.5s.301-.883.662-1.123C6.026 10.134 6.501 10 7 10c.356 0 .7.068 1 .196V4.41a1 1 0 0 1 .804-.98l1.5-.3a1 1 0 0 1 1.196.98"/>
          </svg>
        <span class="fs-4">
            {{ config["SITE_NAME"] }}
        </span>
    </a>

    {% if current_user.is_authenticated %}
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link {{ 'active' if request.endpoint == 'main.dashboard' }}"
                href="{{ url_for('main.dashboard') }}">Dashboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {{ 'active' if request.endpoint == 'main.music' }}"
                href="{{ url_for('main.music') }}">Music</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
        </li>
    </ul>
    {% endif %}
</header>

app/templates/partials/wtf.html
{% macro form_field(field, autofocus) %}
{%- if field.type == 'BooleanField' %}
<div class="form-check mb-3">
  {{ field(class='form-check-input') }}
  {{ field.label(class='form-check-label') }}
</div>
{%- elif field.type == 'RadioField' %}
{{ field.label(class='form-label') }}
{%- for item in field %}
<div class="form-check{% if loop.last %} mb-3{% endif %}">
  {{ item(class='form-check-input') }}
  {{ item.label(class='form-check-label') }}
</div>
{%- endfor %}
{%- elif field.type == 'SelectField' %}
{{ field.label(class='form-label') }}
{% if field.errors %}
{% if autofocus %}
{{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
{% else %}
{{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
{% endif %}
{%- for error in field.errors %}
<div class="invalid-feedback mb-3">{{ error }}</div>
{%- endfor %}
{% else %}
{{ field(class="form-select mb-3" % extra_classes, **kwargs)|safe }}
{% endif %}
{%- elif field.type == 'TextAreaField' %}
<div class="mb-3">
  {{ field.label(class='form-label') }}
  {% if autofocus %}
  {{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
  {% else %}
  {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
  {% endif %}
  {%- for error in field.errors %}
  <div class="invalid-feedback">{{ error }}</div>
  {%- endfor %}
</div>
{%- elif field.type == 'SubmitField' %}
{{ field(class='btn btn-primary mb-3') }}
{%- else %}
<div class="mb-3">
  {{ field.label(class='form-label') }}
  {% if autofocus %}
  {{ field(class='form-control' + (' is-invalid' if field.errors else ''), autofocus=True) }}
  {% else %}
  {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
  {% endif %}
  {%- for error in field.errors %}
  <div class="invalid-feedback">{{ error }}</div>
  {%- endfor %}
</div>
{%- endif %}
{% endmacro %}

{% macro quick_form(form, action="", method="post", id="", novalidate=False, enctype="") %}
<form {%- if enctype !=None %} enctype="{{ enctype }}" {% endif -%} {%- if action !=None %} action="{{ action }}" {%
  endif -%} {%- if method %} method="{{ method }}" {% endif -%} {%- if id %} id="{{ id }}" {% endif -%} {%- if
  novalidate %} novalidate{% endif -%}>
  {{ form.hidden_tag() }}
  {%- for field, errors in form.errors.items() %}
  {%- if form[field].widget.input_type == 'hidden' %}
  {%- for error in errors %}
  <div class="invalid-feedback">{{ error }}</div>
  {%- endfor %}
  {%- endif %}
  {%- endfor %}

  {% set ns = namespace(first_field=true) %}
  {%- for field in form %}
  {% if field.widget.input_type != 'hidden' -%}
  {{ form_field(field, ns.first_field) }}
  {% set ns.first_field = false %}
  {%- endif %}
  {%- endfor %}
</form>
{% endmacro %}